import express from "express";
import isAuth from "../middlewares/isAuth.js";
import { analyzeResume } from "../controllers/interviewcontroller.js";
import { upload } from "../middlewares/multer.js";
import { generateQuestions } from "../controllers/interviewcontroller.js";
import { submitAnswer } from "../controllers/interviewcontroller.js";
import { finishInterview } from "../controllers/interviewcontroller.js";
import { getMyInterview } from "../controllers/interviewcontroller.js";
import { getInterviewReport } from "../controllers/interviewcontroller.js";
const interviewRouter=express.Router();
interviewRouter.post("/resume",isAuth,upload.single("resume"),analyzeResume);
interviewRouter.post("/generate-questions",isAuth,generateQuestions);
interviewRouter.post("/submit-answer",isAuth,submitAnswer);
interviewRouter.post("/finish",isAuth,finishInterview);
interviewRouter.get("/get-interview",isAuth,getMyInterview);
interviewRouter.get("/report/:id",isAuth,getInterviewReport);
export default interviewRouter;